### ISSUE TITLE
Some theoretical problems want to learn from you

### ISSUE THREAD

**Issue by satuoqaq** [JunruiXiao/PAOD#1]
Thank you for your excellent work about PAOD!!!
I have some question about theoretical problems want to learn from you.
1. compare with TOOD，you use DCN enhance with two concat features after decouple two task,for enhancing two task' consistence ,but TOOD do these things with share feature,  What are the advantages of our approach？
2. How do you choose iou branch instead of GFL/VFL ? and whether there is conflict between quality predict branch and GFL/VFL? 
I hope you can tell me the understanding of these questions. I would appreciate your reply！

**Comment by JunruiXiao** [comment]
Hi, thanks for your interest in our work.
1.  We aurge that the detector should leverage both the shared and specific information for two tasks (i.e. classification and regression) and attempt to find a tradeoff. Therefore, we designed IAM for aggregating the iterative features, and the MCM for mutually constraining the consistency of two tasks by using a learnable offset. You can check the paper for more information.
2. We have not done this experiment due to time and equipment limitations, you can have a try.

**Comment by JunruiXiao** [comment]
> 

Hi, thanks for your interest in our work.

We aurge that the detector should leverage both the shared and specific information for two tasks (i.e. classification and regression) and attempt to find a tradeoff. Therefore, we designed IAM for aggregating the iterative features, and the MCM for mutually constraining the consistency of two tasks by using a learnable offset. You can check the paper for more information.
We have not done this experiment due to time and equipment limitations, you can have a try.

**Comment by JunruiXiao** [comment]
> Thank you for your excellent work about PAOD!!! I have some question about theoretical problems want to learn from you.
> 
> 1. compare with TOOD，you use DCN enhance with two concat features after decouple two task,for enhancing two task' consistence ,but TOOD do these things with share feature,  What are the advantages of our approach？
> 2. How do you choose iou branch instead of GFL/VFL ? and whether there is conflict between quality predict branch and GFL/VFL?
>    I hope you can tell me the understanding of these questions. I would appreciate your reply！

Hi, thanks for your interest in our work.

1. We aurge that the detector should leverage both the shared and specific information for two tasks (i.e. classification and regression) and attempt to find a tradeoff. Therefore, we designed IAM for aggregating the iterative features, and the MCM for mutually constraining the consistency of two tasks by using a learnable offset. You can check the paper for more information.
2. We have not done this experiment due to time and equipment limitations, you can have a try.
